# GitHub Pages
# None of these can actually be changed
safe:     true
lsi:      false
pygments: true

# Formatting
markdown: redcarpet
redcarpet:
  extensions: [
    "autolink"
  , "tables"
  , "strikethrough"
  , "with_toc_data"
  , "fenced_code_blocks"
  , "no_intra_emphasis"
  ]

# Permalinks
permalink: pretty

# Project specific
baseurl:      /VanillaDocs
title:        Vanilla Docs
tagline:      Vanilla Documentation
description:  "Documentation for Vanilla Forums"
url:          http://vanillaforums.github.io/VanillaDocs
