safe: true
lsi: false
pygments: true

baseurl: /VanillaDocs
permalink: pretty

markdown: redcarpet
redcarpet:
  extensions: [
    "no_intra_emphasis",
    "fenced_code_blocks",
    "autolink",
    "tables",
    "with_toc_data",
    "strikethrough"
  ]

exclude: [
  "bower_components",
  "node_modules",
  "package.json",
  "bower.json",
  "gulpfile.js"
]
